# Generated by Django 4.2.7 on 2024-01-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirmpassword',
        ),
    ]
