# Generated by Django 4.2.7 on 2024-01-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('email', models.TextField(db_column='email', null=True)),
                ('number', models.TextField(db_column='number', null=True)),
                ('text', models.TextField(db_column='text', null=True)),
            ],
        ),
    ]
