# Generated by Django 4.2.7 on 2023-12-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_column='title', null=True)),
                ('description', models.TextField(db_column='description', null=True)),
                ('image', models.ImageField(db_column='image', null=True, upload_to='image')),
                ('price', models.PositiveIntegerField(db_column='price', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('email', models.TextField(db_column='email', null=True)),
                ('number', models.TextField(db_column='number', null=True)),
                ('password', models.TextField(db_column='password', null=True)),
            ],
            options={
                'db_table': 'seller_signin',
            },
        ),
    ]
