# Generated by Django 4.2.7 on 2023-12-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(db_column='category', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.TextField(db_column='product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.TextField(db_column='quantity', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.TextField(db_column='stock', null=True),
        ),
    ]
