# Generated by Django 4.2.7 on 2023-12-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_product_title_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='products'),
        ),
    ]
