# Generated by Django 4.2.7 on 2024-01-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
