# Generated by Django 4.2.7 on 2024-01-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_category_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
