# Generated by Django 4.2.7 on 2024-01-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(db_column='product', null=True)),
                ('description', models.TextField(db_column='description', null=True)),
                ('image', models.ImageField(db_column='image', null=True, upload_to='products')),
                ('stock', models.TextField(db_column='stock', null=True)),
                ('quantity', models.TextField(db_column='quantity', null=True)),
                ('price', models.PositiveIntegerField(db_column='price', null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
            ],
        ),
    ]
